### ISSUE TITLE
Creating new games

### ISSUE THREAD

**Issue by szlend** [szlend/mana#7]
We need a form for creating new games.

The form only has one field for now, which is the name of the game.

GET /games/new
- renders the form

POST /games
- creates a game
  - Mana.GameSupervisor.create_game(name)) (returns {:ok, pid} on success, {:error, reason} on failure)
- redirects to /games/game_name
- it should show an error if the game already exists

**Comment by szlend** [comment]
It might be a good idea to create a model for this form, so we can use validations.

``` elixir
embedded_schema do
  # fields
end
```

**Comment by usoban** [comment]
done
